language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -e .
# command to run tests
script:
  - python tests/test_run.py # or py.test for Python versions 3.5 and below
  - python tests/test_rollout_supervisor.py
  - python tests/test_losss.py
  - python tests/test_initial_state.py
